version: '{build}'
image: Visual Studio 2022
configuration: Release
platform: Any CPU

skip_commits:
  files:
  - .github/*
  - doc/*
  - readme.md
  - license.md

cache:
  - packages -> packet.lock
  - paket-files -> packet.lock
  - '%USERPROFILE%\.nuget\packages -> packet.lock, global.json'

environment:
  CHOCO_API_KEY:
    secure: oSM1kJpS3CZN3XVnDWMEGfivr5hW3NR6KRsCjqAimtrv9zvbPObZLgsJ3ZthmkQs

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: dotnet tool restore
- cmd: dotnet paket restore
- cmd: msbuild Confuser2.sln @appveyor_restore.rsp /m

build:
  project: Confuser2.sln
  verbosity: minimal 
  parallel: true

after_build:
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION\net50;
    . 7z a ..\..\..\..\ConfuserEx-CLI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location ConfuserEx\bin\$env:CONFIGURATION\net50-windows;
    . 7z a ..\..\..\..\ConfuserEx-GUI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION\net50;
    . 7z a ..\..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location;
    Push-Location ConfuserEx\bin\$env:CONFIGURATION\net50-windows;
    . 7z a ..\..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml" -y;
    Pop-Location

artifacts:
- path: ConfuserEx*.zip
- path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
  name: ConfuserEx.MSBuild

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

on_failure:
- appveyor PushArtifact msbuild.binlog

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/7ff0ea601d40c1b3fcaa
  on_build_success: true
  on_build_failure: true

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  auth_token:
    secure: k2MIY7tKQEsg6+w3QIxMx6ptoBccUgOadKA1I8O9myFZS4SBdEINCbjGwALZrhdm
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: KSGvC66WIcadFq9WgN+SQVRAkYFojRmqmmiDlJP4CqmpZOGcOgT0tgg1MkWw6glg
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://nuget.pkg.github.com/mkaring/index.json
  api_key:
    secure: k2MIY7tKQEsg6+w3QIxMx6ptoBccUgOadKA1I8O9myFZS4SBdEINCbjGwALZrhdm
  username:
    secure: NGDRiYcrJaLN2PkRszWIVg==
  on:
    APPVEYOR_REPO_TAG: true
after_deploy:
- pwsh: >-
    if ($env:APPVEYOR_REPO_TAG -eq $true) {
        Copy-Item -Path ConfuserEx.zip -Destination .\chocolatey-packages\confuserex\tools
        Copy-Item -Path ConfuserEx-CLI.zip -Destination .\chocolatey-packages\confuserex.portable\tools
        .\chocolatey-packages\New-ChocolateyPackage.ps1 -PackageVersion $env:APPVEYOR_REPO_TAG_NAME
        choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
        Get-ChildItem -Path .\chocolatey-packages -Filter *.nupkg | ForEach-Object {
            choco push $_.FullName --source https://push.chocolatey.org/
        }
    }
