version: '{build}'
image: Visual Studio 2019
configuration: Release
platform: Any CPU

skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

cache:
  - packages -> packet.lock
  - paket-files -> packet.lock
  - '%USERPROFILE%\.nuget\packages -> packet.lock, global.json'

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: .paket\paket.exe restore
- cmd: msbuild Confuser2.sln @appveyor_restore.rsp /m

build:
  project: Confuser2.sln
  verbosity: minimal 
  parallel: true

after_build:
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx-CLI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location ConfuserEx\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx-GUI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location;
    Push-Location ConfuserEx\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml" -y;
    Pop-Location

artifacts:
- path: ConfuserEx*.zip
- path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
  name: ConfuserEx.MSBuild

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

on_failure:
- appveyor PushArtifact msbuild.binlog

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/7ff0ea601d40c1b3fcaa
  on_build_success: true
  on_build_failure: true

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  auth_token:
    secure: k2MIY7tKQEsg6+w3QIxMx6ptoBccUgOadKA1I8O9myFZS4SBdEINCbjGwALZrhdm
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: yqARg8GA5EIFGPVpYPZeS3I5gjsByMvYLVfXylpC9mF33W4Z40tAmE9q0/yf2Xne
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://nuget.pkg.github.com/mkaring/index.json
  api_key:
    secure: k2MIY7tKQEsg6+w3QIxMx6ptoBccUgOadKA1I8O9myFZS4SBdEINCbjGwALZrhdm
  username:
    secure: NGDRiYcrJaLN2PkRszWIVg==
  on:
    APPVEYOR_REPO_TAG: true
